/*
 * generated by Xtext 2.9.2
 */
package eu.ttc.dataflow.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDataflowDSLScopeProvider extends DelegatingScopeProvider {
}
