//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2016.LiveContest.LaunchConfiguration
{
    
    
    /// <summary>
    /// The default implementation of the Configuration class
    /// </summary>
    [XmlNamespaceAttribute("http://transformation-tool-contest.eu/2016/launch")]
    [XmlNamespacePrefixAttribute("lc")]
    [ModelRepresentationClassAttribute("http://transformation-tool-contest.eu/2016/launch#//Configuration/")]
    public class Configuration : ModelElement, IConfiguration, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Dataflow property
        /// </summary>
        private IDataflow _dataflow;
        
        /// <summary>
        /// The backing field for the Models property
        /// </summary>
        private ObservableCompositionList<IModel> _models;
        
        private static IClass _classInstance;
        
        public Configuration()
        {
            this._models = new ObservableCompositionList<IModel>(this);
            this._models.CollectionChanging += this.ModelsCollectionChanging;
            this._models.CollectionChanged += this.ModelsCollectionChanged;
        }
        
        /// <summary>
        /// The dataflow property
        /// </summary>
        [XmlElementNameAttribute("dataflow")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        public virtual IDataflow Dataflow
        {
            get
            {
                return this._dataflow;
            }
            set
            {
                if ((this._dataflow != value))
                {
                    IDataflow old = this._dataflow;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnDataflowChanging(e);
                    this.OnPropertyChanging("Dataflow", e);
                    this._dataflow = value;
                    if ((old != null))
                    {
                        old.Parent = null;
                        old.Deleted -= this.OnResetDataflow;
                    }
                    if ((value != null))
                    {
                        value.Parent = this;
                        value.Deleted += this.OnResetDataflow;
                    }
                    this.OnDataflowChanged(e);
                    this.OnPropertyChanged("Dataflow", e);
                }
            }
        }
        
        /// <summary>
        /// The models property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [XmlElementNameAttribute("models")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [ConstantAttribute()]
        public virtual IListExpression<IModel> Models
        {
            get
            {
                return this._models;
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new ConfigurationChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new ConfigurationReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://transformation-tool-contest.eu/2016/launch#//Configuration/")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired before the Dataflow property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> DataflowChanging;
        
        /// <summary>
        /// Gets fired when the Dataflow property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> DataflowChanged;
        
        /// <summary>
        /// Raises the DataflowChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnDataflowChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.DataflowChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the DataflowChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnDataflowChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.DataflowChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the Dataflow property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetDataflow(object sender, System.EventArgs eventArgs)
        {
            this.Dataflow = null;
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the Models property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void ModelsCollectionChanging(object sender, NMF.Collections.ObjectModel.NotifyCollectionChangingEventArgs e)
        {
            this.OnCollectionChanging("Models", e);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the Models property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void ModelsCollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("Models", e);
        }
        
        /// <summary>
        /// Gets the relative URI fragment for the given child model element
        /// </summary>
        /// <returns>A fragment of the relative URI</returns>
        /// <param name="element">The element that should be looked for</param>
        protected override string GetRelativePathForNonIdentifiedChild(IModelElement element)
        {
            if ((element == this.Dataflow))
            {
                return ModelHelper.CreatePath("Dataflow");
            }
            int modelsIndex = ModelHelper.IndexOfReference(this.Models, element);
            if ((modelsIndex != -1))
            {
                return ModelHelper.CreatePath("models", modelsIndex);
            }
            return base.GetRelativePathForNonIdentifiedChild(element);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "DATAFLOW"))
            {
                return this.Dataflow;
            }
            if ((reference == "MODELS"))
            {
                if ((index < this.Models.Count))
                {
                    return this.Models[index];
                }
                else
                {
                    return null;
                }
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "MODELS"))
            {
                return this._models;
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "DATAFLOW"))
            {
                this.Dataflow = ((IDataflow)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "DATAFLOW"))
            {
                return new DataflowProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "DATAFLOW"))
            {
                return new DataflowProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://transformation-tool-contest.eu/2016/launch#//Configuration/")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Configuration class
        /// </summary>
        public class ConfigurationChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Configuration _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public ConfigurationChildrenCollection(Configuration parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    if ((this._parent.Dataflow != null))
                    {
                        count = (count + 1);
                    }
                    count = (count + this._parent.Models.Count);
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.DataflowChanged += this.PropagateValueChanges;
                this._parent.Models.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.DataflowChanged -= this.PropagateValueChanges;
                this._parent.Models.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                if ((this._parent.Dataflow == null))
                {
                    IDataflow dataflowCasted = item.As<IDataflow>();
                    if ((dataflowCasted != null))
                    {
                        this._parent.Dataflow = dataflowCasted;
                        return;
                    }
                }
                IModel modelsCasted = item.As<IModel>();
                if ((modelsCasted != null))
                {
                    this._parent.Models.Add(modelsCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Dataflow = null;
                this._parent.Models.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if ((item == this._parent.Dataflow))
                {
                    return true;
                }
                if (this._parent.Models.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                if ((this._parent.Dataflow != null))
                {
                    array[arrayIndex] = this._parent.Dataflow;
                    arrayIndex = (arrayIndex + 1);
                }
                IEnumerator<IModelElement> modelsEnumerator = this._parent.Models.GetEnumerator();
                try
                {
                    for (
                    ; modelsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = modelsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    modelsEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                if ((this._parent.Dataflow == item))
                {
                    this._parent.Dataflow = null;
                    return true;
                }
                IModel modelItem = item.As<IModel>();
                if (((modelItem != null) 
                            && this._parent.Models.Remove(modelItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Dataflow).Concat(this._parent.Models).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the Configuration class
        /// </summary>
        public class ConfigurationReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private Configuration _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public ConfigurationReferencedElementsCollection(Configuration parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    if ((this._parent.Dataflow != null))
                    {
                        count = (count + 1);
                    }
                    count = (count + this._parent.Models.Count);
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.DataflowChanged += this.PropagateValueChanges;
                this._parent.Models.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.DataflowChanged -= this.PropagateValueChanges;
                this._parent.Models.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                if ((this._parent.Dataflow == null))
                {
                    IDataflow dataflowCasted = item.As<IDataflow>();
                    if ((dataflowCasted != null))
                    {
                        this._parent.Dataflow = dataflowCasted;
                        return;
                    }
                }
                IModel modelsCasted = item.As<IModel>();
                if ((modelsCasted != null))
                {
                    this._parent.Models.Add(modelsCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.Dataflow = null;
                this._parent.Models.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if ((item == this._parent.Dataflow))
                {
                    return true;
                }
                if (this._parent.Models.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                if ((this._parent.Dataflow != null))
                {
                    array[arrayIndex] = this._parent.Dataflow;
                    arrayIndex = (arrayIndex + 1);
                }
                IEnumerator<IModelElement> modelsEnumerator = this._parent.Models.GetEnumerator();
                try
                {
                    for (
                    ; modelsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = modelsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    modelsEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                if ((this._parent.Dataflow == item))
                {
                    this._parent.Dataflow = null;
                    return true;
                }
                IModel modelItem = item.As<IModel>();
                if (((modelItem != null) 
                            && this._parent.Models.Remove(modelItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.Dataflow).Concat(this._parent.Models).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the dataflow property
        /// </summary>
        private sealed class DataflowProxy : ModelPropertyChange<IConfiguration, IDataflow>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public DataflowProxy(IConfiguration modelElement) : 
                    base(modelElement)
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override IDataflow Value
            {
                get
                {
                    return this.ModelElement.Dataflow;
                }
                set
                {
                    this.ModelElement.Dataflow = value;
                }
            }
            
            /// <summary>
            /// Registers an event handler to subscribe specifically on the changed event for this property
            /// </summary>
            /// <param name="handler">The handler that should be subscribed to the property change event</param>
            protected override void RegisterChangeEventHandler(System.EventHandler<NMF.Expressions.ValueChangedEventArgs> handler)
            {
                this.ModelElement.DataflowChanged += handler;
            }
            
            /// <summary>
            /// Registers an event handler to subscribe specifically on the changed event for this property
            /// </summary>
            /// <param name="handler">The handler that should be unsubscribed from the property change event</param>
            protected override void UnregisterChangeEventHandler(System.EventHandler<NMF.Expressions.ValueChangedEventArgs> handler)
            {
                this.ModelElement.DataflowChanged -= handler;
            }
        }
    }
}

