//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2016.LiveContest.Dataflow
{
    
    
    /// <summary>
    /// The public interface for AddToContainer
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(AddToContainer))]
    [XmlDefaultImplementationTypeAttribute(typeof(AddToContainer))]
    public interface IAddToContainer : IModelElement, IElement
    {
        
        /// <summary>
        /// The listField property
        /// </summary>
        string ListField
        {
            get;
            set;
        }
        
        /// <summary>
        /// The value property
        /// </summary>
        IExpression Value
        {
            get;
            set;
        }
        
        /// <summary>
        /// The position property
        /// </summary>
        IExpression Position
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the ListField property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ListFieldChanging;
        
        /// <summary>
        /// Gets fired when the ListField property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ListFieldChanged;
        
        /// <summary>
        /// Gets fired before the Value property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ValueChanging;
        
        /// <summary>
        /// Gets fired when the Value property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ValueChanged;
        
        /// <summary>
        /// Gets fired before the Position property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> PositionChanging;
        
        /// <summary>
        /// Gets fired when the Position property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> PositionChanged;
    }
}

