//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2016.LiveContest.Dataflow
{
    
    
    /// <summary>
    /// The public interface for AllInstances
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(AllInstances))]
    [XmlDefaultImplementationTypeAttribute(typeof(AllInstances))]
    public interface IAllInstances : IModelElement, IElement
    {
        
        /// <summary>
        /// The field property
        /// </summary>
        string Field
        {
            get;
            set;
        }
        
        /// <summary>
        /// The model property
        /// </summary>
        string Model
        {
            get;
            set;
        }
        
        /// <summary>
        /// The packageName property
        /// </summary>
        string PackageName
        {
            get;
            set;
        }
        
        /// <summary>
        /// The typeName property
        /// </summary>
        string TypeName
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Field property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FieldChanging;
        
        /// <summary>
        /// Gets fired when the Field property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FieldChanged;
        
        /// <summary>
        /// Gets fired before the Model property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ModelChanging;
        
        /// <summary>
        /// Gets fired when the Model property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ModelChanged;
        
        /// <summary>
        /// Gets fired before the PackageName property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> PackageNameChanging;
        
        /// <summary>
        /// Gets fired when the PackageName property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> PackageNameChanged;
        
        /// <summary>
        /// Gets fired before the TypeName property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TypeNameChanging;
        
        /// <summary>
        /// Gets fired when the TypeName property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TypeNameChanged;
    }
}

