//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2016.LiveContest.Dataflow
{
    
    
    /// <summary>
    /// The public interface for BinaryOperation
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(BinaryOperation))]
    [XmlDefaultImplementationTypeAttribute(typeof(BinaryOperation))]
    public interface IBinaryOperation : IModelElement, IExpression
    {
        
        /// <summary>
        /// The operator property
        /// </summary>
        Nullable<BinaryOperator> Operator
        {
            get;
            set;
        }
        
        /// <summary>
        /// The leftExpression property
        /// </summary>
        IExpression LeftExpression
        {
            get;
            set;
        }
        
        /// <summary>
        /// The rightExpression property
        /// </summary>
        IExpression RightExpression
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Operator property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OperatorChanging;
        
        /// <summary>
        /// Gets fired when the Operator property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OperatorChanged;
        
        /// <summary>
        /// Gets fired before the LeftExpression property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> LeftExpressionChanging;
        
        /// <summary>
        /// Gets fired when the LeftExpression property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> LeftExpressionChanged;
        
        /// <summary>
        /// Gets fired before the RightExpression property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> RightExpressionChanging;
        
        /// <summary>
        /// Gets fired when the RightExpression property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> RightExpressionChanged;
    }
}

