//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2016.LiveContest.Dataflow
{
    
    
    /// <summary>
    /// The public interface for FieldReference
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(FieldReference))]
    [XmlDefaultImplementationTypeAttribute(typeof(FieldReference))]
    public interface IFieldReference : IModelElement, IExpression
    {
        
        /// <summary>
        /// The field property
        /// </summary>
        string Field
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Field property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FieldChanging;
        
        /// <summary>
        /// Gets fired when the Field property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FieldChanged;
    }
}

