//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2016.LiveContest.Dataflow
{
    
    
    /// <summary>
    /// The public interface for ForEach
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(ForEach))]
    [XmlDefaultImplementationTypeAttribute(typeof(ForEach))]
    public interface IForEach : IModelElement, IElement
    {
        
        /// <summary>
        /// The listField property
        /// </summary>
        string ListField
        {
            get;
            set;
        }
        
        /// <summary>
        /// The itemField property
        /// </summary>
        string ItemField
        {
            get;
            set;
        }
        
        /// <summary>
        /// The positionField property
        /// </summary>
        string PositionField
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the ListField property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ListFieldChanging;
        
        /// <summary>
        /// Gets fired when the ListField property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ListFieldChanged;
        
        /// <summary>
        /// Gets fired before the ItemField property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ItemFieldChanging;
        
        /// <summary>
        /// Gets fired when the ItemField property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ItemFieldChanged;
        
        /// <summary>
        /// Gets fired before the PositionField property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> PositionFieldChanging;
        
        /// <summary>
        /// Gets fired when the PositionField property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> PositionFieldChanged;
    }
}

