//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2016.LiveContest.Dataflow
{
    
    
    /// <summary>
    /// The public interface for GetFeature
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(GetFeature))]
    [XmlDefaultImplementationTypeAttribute(typeof(GetFeature))]
    public interface IGetFeature : IModelElement, IElement
    {
        
        /// <summary>
        /// The objectField property
        /// </summary>
        string ObjectField
        {
            get;
            set;
        }
        
        /// <summary>
        /// The valueField property
        /// </summary>
        string ValueField
        {
            get;
            set;
        }
        
        /// <summary>
        /// The feature property
        /// </summary>
        string Feature
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the ObjectField property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ObjectFieldChanging;
        
        /// <summary>
        /// Gets fired when the ObjectField property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ObjectFieldChanged;
        
        /// <summary>
        /// Gets fired before the ValueField property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ValueFieldChanging;
        
        /// <summary>
        /// Gets fired when the ValueField property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ValueFieldChanged;
        
        /// <summary>
        /// Gets fired before the Feature property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FeatureChanging;
        
        /// <summary>
        /// Gets fired when the Feature property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FeatureChanged;
    }
}

