//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2016.LiveContest.Dataflow
{
    
    
    /// <summary>
    /// The public interface for SetFeature
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(SetFeature_))]
    [XmlDefaultImplementationTypeAttribute(typeof(SetFeature_))]
    public interface ISetFeature : IModelElement, IElement
    {
        
        /// <summary>
        /// The objectField property
        /// </summary>
        string ObjectField
        {
            get;
            set;
        }
        
        /// <summary>
        /// The feature property
        /// </summary>
        string Feature
        {
            get;
            set;
        }
        
        /// <summary>
        /// The value property
        /// </summary>
        IExpression Value
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the ObjectField property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ObjectFieldChanging;
        
        /// <summary>
        /// Gets fired when the ObjectField property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ObjectFieldChanged;
        
        /// <summary>
        /// Gets fired before the Feature property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FeatureChanging;
        
        /// <summary>
        /// Gets fired when the Feature property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FeatureChanged;
        
        /// <summary>
        /// Gets fired before the Value property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ValueChanging;
        
        /// <summary>
        /// Gets fired when the Value property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ValueChanged;
    }
}

