//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2016.LiveContest.Dataflow
{
    
    
    /// <summary>
    /// The public interface for UnaryOperation
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(UnaryOperation))]
    [XmlDefaultImplementationTypeAttribute(typeof(UnaryOperation))]
    public interface IUnaryOperation : IModelElement, IExpression
    {
        
        /// <summary>
        /// The operator property
        /// </summary>
        Nullable<UnaryOperator> Operator
        {
            get;
            set;
        }
        
        /// <summary>
        /// The expression property
        /// </summary>
        IExpression Expression
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Operator property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OperatorChanging;
        
        /// <summary>
        /// Gets fired when the Operator property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OperatorChanged;
        
        /// <summary>
        /// Gets fired before the Expression property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ExpressionChanging;
        
        /// <summary>
        /// Gets fired when the Expression property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> ExpressionChanged;
    }
}

