/*
 * generated by Xtext 2.9.2
 */
package eu.ttc.dataflow.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DataflowDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("eu/ttc/dataflow/parser/antlr/internal/InternalDataflowDSL.tokens");
	}
}
