/*
 * generated by Xtext 2.9.2
 */
package eu.ttc.dataflow.scoping

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class DataflowDSLScopeProvider extends AbstractDeclarativeScopeProvider {

}
